<?php

namespace onefasteuro\ShopifyApps\Tests;


use onefasteuro\ShopifyApps\ServiceProvider;
use onefasteuro\ShopifyClient\ShopifyClientServiceProvider;
use Orchestra\Testbench\TestCase as BaseTestCase;
use PDO;
	
class TestCase extends BaseTestCase
{
		
	protected function getPackageProviders($app)
	{
		return [ServiceProvider::class, ShopifyClientServiceProvider::class];
	}
	
	
	protected function setUp(): void
	{
		parent::setUp(); // TODO: Change the autogenerated stub
		
	}
	
	
	
	protected function tearDown(): void
	{
		parent::tearDown(); // TODO: Change the autogenerated stub
	}
	
	
	/**
	 * Define environment setup.
	 *
	 * @param  \Illuminate\Foundation\Application  $app
	 * @return void
	 */
	protected function getEnvironmentSetUp($app)
	{
		// Setup default database to use sqlite :memory:
		$app['config']->set('database.default', 'app');
		$app['config']->set('database.connections.app', [
			'driver' => 'sqlite',
			'database' => ':memory:',
			'prefix' => '',
		]);
		
		$app['config']->set('session.driver', 'array');
		
		
		$app['config']->set('app.key', 'base64:pulZAoVJxNN6JSeDIhHNvpXZL5UGJmQU2BldkmtexoY=');
	}
}
